### ISSUE TITLE
Add new table of junction for fittings

### ISSUE THREAD

**Issue by JinIgarashi** [JinIgarashi/postgis2qfield#1]
Add a new table which named "junction" to GeoPackage template.
Attached file is SQL for create table of "junction".

[junction table.txt](https://github.com/WASAC/postgis2qfield/files/4238866/junction.table.txt)

**Comment by JinIgarashi** [comment]
@mirankunda 

Hi, I added junction table as your requested. Please check new source code as following methods.

- Open Command Prompt.
- Run following command to update source code
```
$ cd C:\python_script\postgis2qfield
$ git pull origin master
```
- Run `run_postgis2qfield.bat`
- Check your exported QGIS project and make sure there is junction layer under template_geopackage and existing_gis_database.

If everything is okay, please close this issue.

**Comment by JinIgarashi** [comment]
@mirankunda 
I reduced the size of icon for junction layer both template and existing. please check it.
please also try to upgrade QGIS version from 3.4 to 3.10.
I think 3.12 will also come very soon after few days ago.

**Comment by mirankunda** [comment]
Well received with thanks,  will I use the same prompt command?  and also
to install QGIS 3.10 I need to reinstall QGIS 3.4?

**Comment by JinIgarashi** [comment]
@mirankunda 
Murakoze cyane. Yeah, you can use the same command to run it.
It is better to install 3.10, because now 3.10 is LTR. Then remove 3.4 from computer. also tell our colleagues to use 3.10
