### ISSUE TITLE
Industrial as type of water connection is not appeared in geopackage and Institution feature count is not appeared  

### ISSUE THREAD

**Issue by mirankunda** [JinIgarashi/postgis2qfield#11]
Industrial as type of water connection is not appeared in geopackage and Institution feature count is not appeared in geopackage @JinIgarashi rwamagana geopackage is attached for reference 
![Capture](https://user-images.githubusercontent.com/60642018/90012884-83ab2480-dca4-11ea-96c1-b0ef2ab8487b.JPG)

[51_Rwamagana_20200812_090957.zip](https://github.com/WASAC/postgis2qfield/files/5062443/51_Rwamagana_20200812_090957.zip)

**Comment by JinIgarashi** [comment]
@mirankunda 
I just checked the condition of QGIS project.

## Issue of Institution
I forgot to enable `Show feature count`. I will update template QGIS project file.

## Issue of Industrial
I will add new layer for `Industrial`.

Both issues are just a matter of template QGIS project file. I will fix it during this weekend.

In others, I created another issue (https://github.com/WASAC/postgis2qfield/issues/12) for icons updating. It requires to be updated all of layers in QGIS project file. This icons updating issue might take some time.
