### ISSUE TITLE
Adding PH chamber and Water meter chamber as type of chamber layer 

### ISSUE THREAD

**Issue by mirankunda** [JinIgarashi/postgis2qfield#16]
![image](https://user-images.githubusercontent.com/60642018/111972170-d6d03a00-8b05-11eb-83cf-e78d07517534.png)
in rural water network we find new type of chambers (PH chamber and Water meter chamber and also other type can be added ) therefore @JinIgarashi  this three type can be added

**Comment by JinIgarashi** [comment]
@mirankunda 
I have some questions before adding those types of chamber.

 ## About `Water meter chamber`
 What does `water meter` mean? If it means `household` connection, we can add `meter_protected ` column into `water_connection` table instead.
If it means flow meter or bulk meter, we may create bulk_meter table together with `meter_protected ` column. Maybe `bulk_meter` table structure might be as follows:

- table name: bulk_meter
- id: serial, primary key
- wss_id: integer
- diameter: Integer
- manufacturer: String
- serial_no: String
- meter_protected: boolean <- this can be used for chamber
- initial_reading: float
- status: Functional, Partially Functional,...
- installation_data: date
- observation: string
- geom: geometry (Point, 4326)

## About `PH chamber`

This PH chamber is for protecting PH meter, isn't it? I think some assets related to water quality is very different from chamber, and it is very significant for water utilities. 
I suggest we create another table for `sampling_points` including `chamber_protected` column. The table might be as below.

- table name: sampling_point
- id: serial, primary key
- chlorine_meter: boolean
- turbidity_meter: boolean
- ph_meter: boolean
- (other types of water quality meter can be added)
- chamber_protected: boolean <- it can be used for chamber
- installation_date: date
- observation: string
- geom: geometry

What do you think my ideas??

**Comment by mirankunda** [comment]
Dear Jin

About *Bulk water meter chamber* I think is enough unless we create new
table of Bulk meter with different column like (
Meter Location Name
Serial Number
Old serial Number
Meter Manufacturer
Year of Manufacture
Meter Type
Meter Class
Nominal Flow
Meter Function
Type writer Reading
Physical Status of Meter
Meter sealing
Meter screen status
Meter Position
Meter Index Status
)
And also for *PH chamber *there is no need of table because is there for
reducing acidity

*here where I stand for my opinion *



        Best regards
*** Eng. Moise Irankunda****
*** BTech in surveying and geomatics Engineering****
***Department: Civil Environmental and Geomatic Engineering ** *

*** GIS Consultant at Esri Rwanda****


****(Sept 2015 Up to June 2016)***

***GIS Survey Officer at EDCL/REG****
*****( 01 July 2016 Up 4 October 2019)*****

****MIS Specialist at Water & Sanitation Corporation ****


*****( 07 October 2019 Up to date )**********
*Contacts:1. Phone:+250788209547****
*               2. ***@***.***
***@***.***> ****

***Measurements is fundamental for Sustainable Development*****

**Comment by JinIgarashi** [comment]
@mirankunda I think we can add `pH chamber` as new type. But it needs to discuss more about adding `meter` information whether it should be as `chamber` or independent table. I still think it is better to have an independent table for meters instead of adding into chamber table. Because information of meters can be used for many purposes, it is quite different from the taste of chamber.

**Comment by JinIgarashi** [comment]
@mirankunda I added `PH chamber` and other small enhancements in this PR (https://github.com/WASAC/postgis2qfield/pull/17).

I added Docker in this repository. So now you can launch the scripts by docker.

```
cd postgis2qfield
git pull origin master
docker pull wasac/postgis2qfield:v1.0.1
```

Then, please create `.env` file by copying `.env.example` file. After that, edit `.env` file to change your database password.

`.env` file
```
DB_USER=postgres
DB_PASSWORD={your password}
DB_HOST=host.docker.internal
DB_PORT=5432
DB_NAME=rwss_assets
DISTRICTS=54
```

After doing database settings, please run docker as follow

```
docker-compose up
```

**Comment by JinIgarashi** [comment]
@mirankunda I have drafted SQL to create `water_meter` table. I put some questions in SQL. Could you confirm?

I need some example values which you expect to input in some fields. So I can design table structure properly.

```sql
CREATE TABLE water_meter
(
    id serial NOT NULL,
    location_name character varying(100) NOT NULL,
    serial_number character varying(50) NOT NULL,
    old_serial_number character varying(50),
    -- Could you provide me the list of manufacturer which you are expecting to be inputted.
    manufacturer character varying(100), 
    manufacture_year integer,
    -- Could you provide me the list of meter_type which you are expecting to be inputted.
    meter_type character varying(50),
    -- Could you provide me the list of mater_class which you are expecting to be inputted.
    mater_class character varying(50),
    -- this nominal_flow is something like 'DN100' for diameter? Please give me an example value.
    nominal_flow double precision,
    -- what is exact meaning? please give me some example which you are expecting in this field.
    meter_function character varying(100),
    -- I can't understand what is 'type writer reading'. What is that?
    type_writer_reading character varying(50),
    -- physical_status is just like 'Full functional', 'Partially functional'...?
    physical_status character varying(50),
    -- is it okay to use boolean either true or false?
    meter_sealing boolean NOT NULL DEFAULT false,
    -- screen status means something like 'visible' or 'unvisible'? Could you give some example values?
    meter_screen_condition character varying(50),
    -- I need some example for this field. Is it like 'vertical', 'horizontal'?
    meter_position character varying(100),
    -- I don't know what is exact meaning of index_status. Could you provide me some examples?
    meter_index_status character varying(100),
    installation_date date,
    input_date date NOT NULL DEFAULT now(),
    geom geometry(PointZ, 4326) NOT NULL,
    CONSTRAINT water_meter_pkey PRIMARY KEY (id)
);
```

**Comment by mirankunda** [comment]
(
    id serial NOT NULL,
    location_name character varying(100) NOT NULL,
    serial_number character varying(50) NOT NULL,
    old_serial_number character varying(50),
    -- Could you provide me the list of manufacturer which you are
expecting to be inputted.
    manufacturer character varying(100), (*Actaris, Endress Hausser,
Itron, Kent, Sappel, Sensus, Shlumberger, Socam, Zener, Flodis, Other,
Not available )*
    manufacture_year integer,
    -- Could you provide me the list of meter_type which you are
expecting to be inputted.
    meter_type character varying(50),(*Single-Jets, Multi-Jets,
Industrial, Ultrasonic, Velocity, Volumetric, Electromagnetic , Other
)*
    -- Could you provide me the list of meter_class which you are
expecting to be inputted.
    mater_class character varying(50),(*A,B,C,D, Other*)
    -- this nominal_flow is something like 'DN100' for diameter?
Please give me an example value.
    nominal_flow double precision,*( 10, 1.5, 2.5, 250 etc the unit
price is m3/h)*
    -- what is exact meaning? please give me some example which you
are expecting in this field.
    meter_function character varying(100),(*Bulk meter (for
reservoir), DMA , for fire hydrant , Other*)
    -- I can't understand what is 'type writer reading'. What is that?
    type_writer_reading character varying(50),( *writer reading can be
: Mechanical, Smart Meter ,Cash water* )
    -- physical_status is just like 'Full functional', 'Partially
functional'...?
    physical_status character varying(50),(* yeah the same *)
    -- is it okay to use boolean either true or false?
    meter_sealing boolean NOT NULL DEFAULT false,*(yeah the same)*
    -- screen status means something like 'visible' or 'unvisible'?
Could you give some example values?
    meter_screen_condition character varying(50),*(Readable , Unreadable )*
    -- I need some example for this field. Is it like 'vertical', 'horizontal'?
    meter_position character varying(100),*( DMA in flow , DMA out flow) *
    -- I don't know what is exact meaning of index_status. Could you
provide me some examples?
    meter_index_status character varying(100), *(just numbers like 9005104 )*
    installation_date date,
    input_date date NOT NULL DEFAULT now(),
    geom geometry(PointZ, 4326) NOT NULL,
    CONSTRAINT water_meter_pkey PRIMARY KEY (id)
);



*Dear Jin here above responses for your consideration *



        Best regards
*** Eng. Moise Irankunda****
*** BTech in surveying and geomatics Engineering****
***Department: Civil Environmental and Geomatic Engineering ** *

*** GIS Consultant at Esri Rwanda****


****(Sept 2015 Up to June 2016)***

***GIS Survey Officer at EDCL/REG****
*****( 01 July 2016 Up 4 October 2019)*****

****MIS Specialist at Water & Sanitation Corporation ****


*****( 07 October 2019 Up to date )**********
*Contacts:1. Phone:+250788209547****
*               2. ***@***.***
***@***.***> ****

***Measurements is fundamental for Sustainable Development*****

**Comment by JinIgarashi** [comment]
I finalized SQL and option values for each columns

## SQL
```sql
CREATE TABLE water_meter
(
    id serial NOT NULL,
	wss_id integer NOT NULL,
    location_name character varying(100) NOT NULL,
    serial_number character varying(50) NOT NULL,
    old_serial_number character varying(50),
    manufacturer character varying(100), 
    manufacture_year integer,
    meter_type character varying(50),
    mater_class character varying(50),
    nominal_flow double precision,
    meter_function character varying(100),
    type_writer_reading character varying(50),
    status integer,
    meter_sealing boolean NOT NULL DEFAULT false,
    meter_screen_condition character varying(50),
    meter_position character varying(100),
    meter_index_status integer,
    installation_date date,
    input_date date NOT NULL DEFAULT now(),
    geom geometry(PointZ, 4326) NOT NULL,
    CONSTRAINT water_meter_pkey PRIMARY KEY (id)
);
```

## Option values
option values for some columns as below (should be appear in QGIS form):
- manufacturer
  - Actaris
  - Endress Hausser
  - Itron
  - Kent
  - Sappel
  - Sensus
  - Shlumberger
  - Socam
  - Zener
  - Flodis
  - Other
  - Not available
- meter_type
  - Single-Jets
  - Multi-Jets
  - Industrial
  - Ultrasonic
  - Velocity
  - Volumetric
  - Electromagnetic
  - Other
- mater_class
  - A
  - B
  - C
  - D
  - Other
- nominal_flow: m3/h
- meter_function
  - DMA
  - Fire Hydrant
  - Other
- type_writer_reading
  - Mechanical
  - Smart Meter
  - Cash water
  - Other
- physical_status
  - Fully functional
  - Partially functional
  - Abandoned
  - Not functional
- meter_screen_condition
  - Readable
  - Unreadable
- meter_position
  - Vertical
  - Horizontal
