### ISSUE TITLE
please add  Complex as water supply system type because is missing only we have Gravity and Pumping 

### ISSUE THREAD

**Issue by mirankunda** [JinIgarashi/postgis2qfield#7]
for example in Nyaruguru we have two system
![example](https://user-images.githubusercontent.com/60642018/86474572-67ca6f80-bd43-11ea-84ab-ab9807e9ea9c.JPG)
 mata and Nyabimata which have water treatment plant so wss_type is Complex @JinIgarashi

**Comment by JinIgarashi** [comment]
@mirankunda 
added complex was_type style into wss(offline) layer.
Please update the source code as usual and check it.

![Screen Shot 2020-07-04 at 9 42 15](https://user-images.githubusercontent.com/2639701/86502170-343b2400-bddb-11ea-8d34-84a8cff74d34.png)
